#! /bin/sh
#   ________
#   | _____ \
#   | |  _/ /      Pim Nelissen
#   | | /__/       https://pim.wtf/
#   | |
#   \_|

# bspwm configuation file.

# Enable sxhkd keybindings.
pgrep -x sxhkd > /dev/null || sxhkd &

# Launch polybar.
$HOME/.config/polybar/launch.sh

# Set wallpaper.
feh --bg-fill $HOME/.wallpapers/mountains.jpeg

# Load BT & Network tray applets.
blueman-manager &
nm-applet &

# Load applications which require X server & WM to have launched.
nextcloud --background &
redshift &

# Set up 8 bspwm workspaces.
bspc monitor -d I II III IV V VI VII VIII

# Borders, gaps and padding to fit polybar.
bspc config border_width         2
bspc config window_gap           15
bspc config top_padding          50

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# bspwm window rules for applications.
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Pavucontrol state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a blueman-manager state=floating
bspc rule -a virt-manager state=floating
bspc rule -a Nextcloud state=floating
bspc rule -a Galculator state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
