#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

nextcloud --background &
redshift &
nitrogen --set-zoom-fill ~/.wallpapers/sf.jpg

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a blueman-manager state=floating
bspc rule -a virt-manager state=floating
bspc rule -a Nextcloud state=floating
bspc rule -a Galculator state=floating
