#! /bin/sh
#   ________ 
#   | _____ \
#   | |  _/ /      Pim Nelissen
#   | | /__/       p1m@disroot.org
#   | |    	   https://pim.wtf/
#   \_|  
#
# BSPWM configuation file.

# Enable sxhkd keybindings.
pgrep -x sxhkd > /dev/null || sxhkd &

# Launch polybar.
$HOME/.config/polybar/launch.sh

# Set wallpaper.
nitrogen --set-zoom-fill ~/.wallpapers/sf.jpg

# Load applications which require X server & WM to have launched.
nextcloud --background &
redshift &

bspc monitor -d I II III IV V VI

# Match the bspwm window gap to the gaps of polybar.
bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspwm window rules for different applications on my system.
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Pavucontrol state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a blueman-manager state=floating
bspc rule -a virt-manager state=floating
bspc rule -a Nextcloud state=floating
bspc rule -a Galculator state=floating
